#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include "sokoban.h"
#include "renderer.h"

char map[H][W] = {
  {WALL, WALL  , WALL  , WALL  , WALL  , WALL  , WALL  , WALL  , WALL  , WALL},
  {WALL, TARGET, GROUND, GROUND, WALL  , GROUND, GROUND, GROUND, GROUND, WALL},
  {WALL, GROUND, CRATE , PLAYER, CRATE , CRATE , GROUND, TARGET, GROUND, WALL},
  {WALL, GROUND, GROUND, GROUND, WALL  , GROUND, GROUND, GROUND, GROUND, WALL},
  {WALL, GROUND, GROUND, GROUND, WALL  , GROUND, GROUND, GROUND, GROUND, WALL},
  {WALL, GROUND, GROUND, GROUND, WALL  , GROUND, GROUND, GROUND, GROUND, WALL},
  {WALL, GROUND, GROUND, GROUND, WALL  , GROUND, GROUND, GROUND, GROUND, WALL},
  {WALL, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, TARGET, GROUND, WALL},
  {WALL, GROUND, GROUND, GROUND, WALL  , GROUND, GROUND, GROUND, GROUND, WALL},
  {WALL, WALL  , WALL  , WALL  , WALL  , WALL  , WALL  , WALL  , WALL  , WALL}
};

int main() {
  run(map);
  return 0;
}

